type TableType =
    | 'Site and Source Energy'
    | 'Site to Source Energy Conversion Factors'
    | 'Building Area'
    | 'End Uses'
    | 'End Uses By Subcategory'
    | 'Utility Use Per Conditioned Floor Area'
    | 'Utility Use Per Total Floor Area'
    | 'Electric Loads Satisfied'
    | 'On-Site Thermal Sources'
    | 'Water Source Summary'
    | 'Setpoint Not Met Criteria'
    | 'Comfort and Setpoint Not Met Summary'
    | 'General'
    | 'Window-Wall Ratio'
    | 'Conditioned Window-Wall Ratio'
    | 'Skylight-Roof Ratio'
    | 'Zone Summary'
    | 'End Uses'
    | 'End Uses By Subcategory'
    | 'Time Not Meeting the Adaptive Comfort Models during Occupied Hours'
    | 'SizingPeriod:DesignDay'
    | 'Weather Statistics File'
    | 'Opaque Exterior'
    | 'Opaque Interior'
    | 'Exterior Fenestration'
    | 'Interior Fenestration'
    | 'Exterior Door'
    | 'Interior Door'
    | 'Interior Lighting'
    | 'Daylighting'
    | 'Exterior Lighting'
    | 'Central Plant'
    | 'Cooling Coils'
    | 'DX Cooling Coils'
    | 'DX Cooling Coil ASHRAE 127 Standard Ratings Report'
    | 'DX Heating Coils'
    | 'Heating Coils'
    | 'Fans'
    | 'Pumps'
    | 'Service Water Heating'
    | 'Zone Sensible Cooling'
    | 'Zone Sensible Heating'
    | 'System Design Air Flow Rates'
    | 'Plant Loop Coincident Design Fluid Flow Rate Adjustments'
    | 'Coil Sizing Summary'
    | 'Economizer'
    | 'Demand Controlled Ventilation using Controller:MechanicalVentilation'
    | 'Time Not Comfortable Based on Simple ASHRAE 55-2004'
    | 'Time Setpoint Not Met'
    | 'Annual Building Sensible Heat Gain Components'
    | 'Peak Cooling Sensible Heat Gain Components'
    | 'Peak Heating Sensible Heat Gain Components'
    | 'Custom Monthly Report'
    | 'Custom Monthly Report'
    | 'Custom Monthly Report';

    export default TableType;